name: Fetch Latest Blog Post Workflow
on:
  schedule:
    - cron: 0 0 * * SAT # Runs weekly, Saturday
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update GitHub Profile README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch Posts from Medium Feed
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "MEDIUM"
          commit_message: "Updated readme with the latest Medium data"
          max_post_count: 10
          feed_list: https://fullstackage.medium.com/feed

      - name: Fetch Videos from Youtube Feed
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          max_post_count: 5
          commit_message: "Updated readme with the latest Youtube data"
          feed_list: https://www.youtube.com/feeds/videos.xml?channel_id=UCRWDR9vuoRny63i464-pZrg